name: Validate terraform fmt
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: terraform fmt check

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Fetch changed files
        uses: tj-actions/changed-files@v37
        id: pr_files

      - name: Download terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Validate terraform format
        run: |
          set +e

          CHECK_STATUS=0

          for changed_file in ${{ steps.pr_files.outputs.all_changed_files }}
          do

            if [[ "${changed_file}" == *.tf ]]
            then
              echo "Checking terraform fmt on ${changed_file}..."
              terraform fmt -check ${changed_file}
              FMT_STATUS=$?

              if [[ ${FMT_STATUS} -ne 0 ]]
              then
                echo "âŒ terraform fmt failed - **${changed_file}**" >> ${GITHUB_STEP_SUMMARY}
                echo '```' >> ${GITHUB_STEP_SUMMARY}
                terraform fmt -diff $changed_file >> ${GITHUB_STEP_SUMMARY}
                echo '```' >> ${GITHUB_STEP_SUMMARY}
                echo "" >> ${GITHUB_STEP_SUMMARY}
                CHECK_STATUS=1
              fi

            fi

          done
          exit $CHECK_STATUS
